name: lzf_music
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.9

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  drift: ^2.28.0
  audio_metadata_reader: ^1.4.2
  path_provider: ^2.1.2
  provider: ^6.1.5
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  window_manager: ^0.5.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  bitsdojo_window: ^0.1.6
  flutter_charset_detector: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true